# Generated by Django 5.2.14 on 2026-05-26 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('month_closure', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monthclosure',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_months', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthclosure',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_closures', to='tenants.property'),
        ),
        migrations.AddField(
            model_name='monthclosure',
            name='reopened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_months', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthclosure',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_closures', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='monthclosure',
            unique_together={('tenant', 'property', 'year', 'month')},
        ),
    ]
