from django.urls import path

from apps.webui import views

urlpatterns = [
    path("", views.root_redirect, name="webui-root"),
    path("app/login/", views.login_page, name="webui-login"),
    path("app/logout/", views.logout_page, name="webui-logout"),
    path("app/context/", views.switch_context, name="webui-context"),
    path("app/", views.dashboard, name="webui-dashboard"),
    path("app/tenants/", views.tenants_page, name="webui-tenants"),
    path("app/modules/", views.modules_page, name="webui-modules"),
    path("app/support/", views.support_page, name="webui-support"),
    path("app/properties/", views.properties_page, name="webui-properties"),
    path("app/areas/", views.areas_page, name="webui-areas"),
    path("app/workers/", views.workers_page, name="webui-workers"),
    path("app/shifts/", views.shifts_page, name="webui-shifts"),
    path("app/shifts-auto/", views.auto_shifts_page, name="webui-auto-shifts"),
    path("app/special-states/", views.special_states_page, name="webui-special-states"),
    path("app/users-permissions/", views.users_permissions_page, name="webui-users-permissions"),
    path("app/imports/", views.imports_page, name="webui-imports"),
    path("app/imports/workers-template/", views.workers_template_download, name="webui-workers-template-download"),
    path("app/imports/shifts-template/", views.shifts_template_download, name="webui-shifts-template-download"),
    path("app/imports/workers-sample/", views.workers_sample_download, name="webui-workers-sample-download"),
    path("app/imports/shifts-sample/", views.shifts_sample_download, name="webui-shifts-sample-download"),
    path("app/backup/", views.backup_page, name="webui-backup"),
    path("app/backup/download/", views.backup_download, name="webui-backup-download"),
    path("app/month-closure/", views.month_closure_page, name="webui-month-closure"),
    path("app/scheduling/", views.scheduling_page, name="webui-scheduling"),
    path("app/scheduling/team-report.pdf", views.scheduling_team_report_pdf, name="webui-scheduling-team-report-pdf"),
    path("app/scheduling/assign/", views.scheduling_assign, name="webui-scheduling-assign"),
    path("app/scheduling/bulk-shift/", views.scheduling_bulk_shift, name="webui-scheduling-bulk-shift"),
    path("app/scheduling/bulk-state/", views.scheduling_bulk_state, name="webui-scheduling-bulk-state"),
    path("app/scheduling/bulk-range-state/", views.scheduling_bulk_range_state, name="webui-scheduling-bulk-range-state"),
    path("app/scheduling/bulk-multi-range-state/", views.scheduling_bulk_multi_range_state, name="webui-scheduling-bulk-multi-range-state"),
    path("app/scheduling/bulk-sundays-state/", views.scheduling_bulk_sundays_state, name="webui-scheduling-bulk-sundays-state"),
    path("app/scheduling/bulk-week-pattern/", views.scheduling_bulk_week_pattern, name="webui-scheduling-bulk-week-pattern"),
    path("app/scheduling/operational-rule/", views.scheduling_operational_rule, name="webui-scheduling-operational-rule"),
    path("app/scheduling/save-range-template/", views.scheduling_save_range_template, name="webui-scheduling-save-range-template"),
    path("app/scheduling/update-range-template/", views.scheduling_update_range_template, name="webui-scheduling-update-range-template"),
    path("app/scheduling/update-range-template-ranges/", views.scheduling_update_range_template_ranges, name="webui-scheduling-update-range-template-ranges"),
    path("app/scheduling/create-range-template-version/", views.scheduling_create_range_template_version, name="webui-scheduling-create-range-template-version"),
    path("app/scheduling/clone-range-template/", views.scheduling_clone_range_template, name="webui-scheduling-clone-range-template"),
    path("app/scheduling/delete-range-template/", views.scheduling_delete_range_template, name="webui-scheduling-delete-range-template"),
    path("app/scheduling/range-template-preview/", views.scheduling_range_template_preview, name="webui-scheduling-range-template-preview"),
    path("app/scheduling/apply-range-template/", views.scheduling_apply_range_template, name="webui-scheduling-apply-range-template"),
    path("app/scheduling/save-week-pattern-template/", views.scheduling_save_week_pattern_template, name="webui-scheduling-save-week-pattern-template"),
    path("app/scheduling/update-week-pattern-template/", views.scheduling_update_week_pattern_template, name="webui-scheduling-update-week-pattern-template"),
    path("app/scheduling/delete-week-pattern-template/", views.scheduling_delete_week_pattern_template, name="webui-scheduling-delete-week-pattern-template"),
    path("app/scheduling/apply-week-pattern-template/", views.scheduling_apply_week_pattern_template, name="webui-scheduling-apply-week-pattern-template"),
    path("app/scheduling/copy-week/", views.scheduling_copy_week, name="webui-scheduling-copy-week"),
    path("app/scheduling/copy-month/", views.scheduling_copy_month, name="webui-scheduling-copy-month"),
    path("app/scheduling/copy-previous-month/", views.scheduling_copy_previous_month, name="webui-scheduling-copy-previous-month"),
    path("app/scheduling/preview-cancel/", views.scheduling_preview_cancel, name="webui-scheduling-preview-cancel"),
    path("app/control/", views.control_page, name="webui-control"),
    path("app/audit-global/", views.audit_global_page, name="webui-audit-global"),
    path("app/audit/", views.audit_page, name="webui-audit"),
    path("app/buk-report/", views.buk_report_page, name="webui-buk-report"),
    path(
        "app/buk-report/compare-log/<int:log_id>/download/",
        views.buk_report_compare_log_download,
        name="webui-buk-report-compare-log-download",
    ),
    path(
        "app/buk-report/compare-logs/download-csv/",
        views.buk_report_compare_logs_csv_download,
        name="webui-buk-report-compare-logs-csv-download",
    ),
]
