# Generated by Django 5.2.14 on 2026-05-26 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BukExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255)),
                ('validation_status', models.CharField(default='unknown', max_length=30)),
                ('errors_count', models.PositiveIntegerField(default=0)),
                ('warnings_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BukExportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sheet_name', models.CharField(default='Reporte carga BUK', max_length=160)),
                ('date_format', models.CharField(default='%d-%m-%Y', max_length=30)),
                ('include_area', models.BooleanField(default=True)),
                ('include_worker_name', models.BooleanField(default=True)),
                ('document_column_name', models.CharField(default='RUT', max_length=100)),
                ('name_column_name', models.CharField(default='Nombre', max_length=100)),
                ('area_column_name', models.CharField(default='Área', max_length=100)),
                ('header_row', models.PositiveIntegerField(default=2)),
                ('first_data_row', models.PositiveIntegerField(default=3)),
                ('export_format', models.CharField(default='xlsx', max_length=20)),
                ('other_settings', models.JSONField(blank=True, default=dict)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buk_configs', to='tenants.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buk_configs', to='tenants.tenant')),
            ],
        ),
    ]
