# Generated by Django 5.2.14 on 2026-05-26 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buk_exports', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bukexportlog',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_buk_exports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bukexportlog',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buk_export_logs', to='tenants.property'),
        ),
        migrations.AddField(
            model_name='bukexportlog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buk_export_logs', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='bukexportconfig',
            unique_together={('tenant', 'property')},
        ),
    ]
