# Generated by Django 5.2.14 on 2026-05-27 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buk_exports', '0002_initial'),
        ('tenants', '0002_tenantsupportaccesssession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BukTemplateCompareLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compared_at', models.DateTimeField(auto_now_add=True)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('sheet_name', models.CharField(default='Reporte carga BUK', max_length=160)),
                ('reference_file_name', models.CharField(blank=True, max_length=255)),
                ('is_compatible', models.BooleanField(default=False)),
                ('errors_count', models.PositiveIntegerField(default=0)),
                ('warnings_count', models.PositiveIntegerField(default=0)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('compared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buk_template_compare_logs', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buk_template_compare_logs', to='tenants.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buk_template_compare_logs', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-compared_at', '-id'],
            },
        ),
    ]
