# Generated by Django 5.2.14 on 2026-05-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buk_exports', '0003_buktemplatecomparelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='buktemplatecomparelog',
            name='reference_file_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='buktemplatecomparelog',
            name='reference_file_size_bytes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
