# Generated by Django 5.2.14 on 2026-06-02 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenantsupportaccesssession'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpropertypermission',
            name='can_manage_areas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpropertypermission',
            name='can_manage_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpropertypermission',
            name='can_use_control',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpropertypermission',
            name='can_view_reports',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RoleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('base_role', models.CharField(choices=[('super_admin', 'Super Administrador'), ('admin', 'Administrador'), ('operator', 'Operador'), ('supervisor', 'Supervisor')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('is_system', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_profiles', to='tenants.tenant')),
            ],
            options={
                'ordering': ['base_role', 'name'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.AddField(
            model_name='usertenantrole',
            name='role_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_assignments', to='users.roleprofile'),
        ),
    ]
