# Generated by Codex on 2026-06-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userpropertypermission_can_manage_areas_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertenantrole",
            name="all_properties_access",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usertenantrole",
            name="property_permissions_template",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
