# Generated by Django 5.2.14 on 2026-05-26 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleactivation',
            name='enabled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enabled_modules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moduleactivation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='moduleactivation',
            unique_together={('tenant', 'module_key')},
        ),
    ]
