# Generated by Django 5.2.14 on 2026-05-26 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
        ('tenants', '0001_initial'),
        ('workers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduleassignment',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tenants.property'),
        ),
        migrations.AddField(
            model_name='scheduleassignment',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='workers.shift'),
        ),
        migrations.AddField(
            model_name='scheduleassignment',
            name='special_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='workers.specialstate'),
        ),
        migrations.AddField(
            model_name='scheduleassignment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='scheduleassignment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduleassignment',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='workers.worker'),
        ),
        migrations.AlterUniqueTogether(
            name='scheduleassignment',
            unique_together={('worker', 'property', 'date')},
        ),
    ]
