# Generated by Django 5.2.14 on 2026-07-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0004_schedulerangetemplate"),
        ("tenants", "0002_tenantsupportaccesssession"),
        ("workers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleAssignmentNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("note", models.CharField(max_length=250)),
                (
                    "property",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="schedule_assignment_notes", to="tenants.property"),
                ),
                (
                    "tenant",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="schedule_assignment_notes", to="tenants.tenant"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="updated_schedule_assignment_notes", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "worker",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="schedule_assignment_notes", to="workers.worker"),
                ),
            ],
            options={
                "ordering": ["date", "worker__last_name", "worker__first_name"],
                "unique_together": {("worker", "property", "date")},
            },
        ),
    ]
